/// <reference path="../app/_base.js" />
/// <reference path="../app/_lang.js" />

(function (app) {
    app.lang.add('ID', {
        "active": "Aktif",
        "add": "Tambah",
        "add_x": function (x) { return "Tambah " + x; },
        "all": "Semua",
        "all_x": function (x) { return "Semua " + x; },
        "buyoff": "Beli putus",
        "cancel": "Batal",
        "choose": "Pilih",
        "choose_x": function (x) { return "Pilih " + x; },
        "city": "Kota",
        "click_or_drop_file": "Klik atau jatuhkan berkas",
        "close": "Tutup",
        "code": "Kode",
        "continue": "Lanjutkan",
        "copy":"Salin",
        "create": "Buat",
        "date": "Tanggal",
        "delete": "Hapus",
        "delete_x": function (x) { return "Hapus " + x; },
        "discard_changes_q": "Buang perubahan?",
        "download": "Unduh",
        "download_template": "Unduh Template",
        "edit": "Ubah",
        "edit_x": function (x) { return "Ubah " + x; },
        "empty": "Kosong",
        "empty_v": "Kosongkan",
        "excel":"Excel",
        "export": "Ekspor",
        "failed": "Gagal",
        "fill": "Isi",
        "finish": "Selesai",
        "get_failed": "Tidak dapat memuat data",
        "height": "Tinggi",
        "history": "Riwayat",
        "id":"ID",
        "image": "Gambar",
        "inactive": "Nonaktif",
        "inbound": "Inbound",
        "label": "Label",
        "loading": "Memuat",
        "login_failed": "Login bermasalah",
        "name": "Nama",
        "new": "Baru",
        "no": "Tidak",
        "not_ok": "Tidak OK",
        "note": "Catatan",
        "num": "No",
        "ok": "Ok",
        "open": "Terbuka",
        "open_v": "Buka",
        "operation_failed": "Operasi gagal",
        "print": "Cetak",
        "print_x": function (x) { return "Cetak " + x; },
        "publish": "Terbitkan",
        "pwd_changed": "Sandi diganti",
        "pwd_missmatch": "Sandi tidak cocok",
        "reload": "Segarkan",
        "save": "Simpan",
        "save_failed": "Tidak dapat menyimpan data",
        "saving": "Menyimpan",
        "start": "Mulai",
        "status": "Status",
        "submit": "Submit",
        "symbol": "Simbol",
        "upload":"Unggah",
        "value": "Nilai",
        "wait": "Tunggu",
        "wh_consignment": "Konsinyasi",
        "yes": "Ya",
    });
})(app);